---
## Mandatory values
flows:
  # Placeholder, this is only necessary, because at least one flow definition is
  # mandatory at the moment.
  - ipv4_dst: 10.0.0.254
    udp_dst: 9999
    base_ratelimit: 1 # 5Mbps

controller_baseurl: 'http://localhost:8080'
ovsdb_addr: 'tcp:192.0.2.20:6632'

## Optional values
# time_step: 2
# limit_step: 2500000
interface_max_rate: 45000000 # 45Mbps
# flowstat_window_size: 5
stat_log_format: csv # options: human, csv
