---
## Mandatory values
flows:
  - ipv4_dst: 10.0.0.1
    udp_dst: 5009
    base_ratelimit: 5000000
  - ipv4_dst: 10.0.0.8
    udp_dst: 5002
    base_ratelimit: 15000000
  - ipv4_dst: 10.0.0.1
    udp_dst: 5003
    base_ratelimit: 25000000
ovsdb_addr: 'tcp:192.0.2.20:6632'

## Optional values
# time_step: 2
# limit_step: 2500000
# interface_max_rate: 5000000
# flowstat_window_size: 5
