# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Test controller

on:
  push:
    paths: [ 'controller/**.py', 'controller/**.yml' ]


jobs:
  code_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        working-directory: controller/
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with pylama
        working-directory: controller/
        run: |
          pip install pylama
          pylama .
      - name: Check documentation style
        continue-on-error: true
        working-directory: controller/
        run: |
          pip install pydocstyle
          pydocstyle --convention=pep257 --add-ignore=D100,D101,D102,D103,D104,D105,D106,D107
  config_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check configs that are intended to be correct
        uses: ibiqlik/action-yamllint@v1.0.0
        with:
          file_or_dir: controller/

  unit_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Install dependencies
        working-directory: controller/
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests with pytest
        working-directory: controller/
        run: |
          python -m pip install --upgrade pytest
          ./test.py --verbose
